# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1b8a707a1b9047ce9953df9c0ca9f0c0fae56bfd1aa6a289ae9bf2a51a4985d0458637b0bd39f066fa22e52af6832afda0eb454e3ccb8557a642c08c08a83895

test:
  secret_key_base: 109d4a5c00f5d1aec0fe82b31139aff9b2370aa7bcfb861e8efe79a4ce3543d36f911052eca7ccc64b78168a592457a50a5fc5634691bf622125690c5835dbcb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
